name 'integrate'
maintainer 'Andrew Holt'
maintainer_email 'andrew@theholts.org'
license 'gplv3'
description 'Installs/Configures integrate'
long_description 'Installs/Configures integrate'
version '0.2.0'
